### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by 0x00Wizard** [FizzyViking/LinkedList-Visualising-with-Manim#3]
Sorry for any inconvenience, I was unable to use this code to visualize linked list because I can't understand your readme file, Please can you explain the cmd or can you simplify it and update the readme file, manim -pql 'filename'.py 'classname'

**Comment by FizzyViking** [comment]
Updated the readme. Otherwise, see https://docs.manim.community/en/stable/tutorials/quickstart.html for more examples. The cmd manim -pql linked.py multiLinkcut should work and produce the splice animation example.
